import type { Tone } from './tone';

/**
 * Slot banks per tone.
 *
 * Every entry is a complete sentence, so any combination of the four slots
 * reads correctly - no grammatical agreement between slots to get wrong. A
 * message is opener + jab + twist + closer, which with ~12 options per slot
 * gives over twenty thousand distinct messages per tone.
 *
 * Placeholders, substituted in RoastEngine:
 *   {nick} {rank} {total} {points} {gap} {gapNext} {streak} {acc}
 * Each tone only uses placeholders that are meaningful for it - {gap} never
 * appears in KING, because the leader has no gap to the leader.
 *
 * Tone rule: sarcastic and playful, aimed at the user's predictions, never at
 * the person. Nothing here insults anyone's intelligence, looks or family.
 */
export interface SlotBank {
  readonly opener: readonly string[];
  readonly jab: readonly string[];
  readonly twist: readonly string[];
  readonly closer: readonly string[];
}

export const TEMPLATES: Record<Tone, SlotBank> = {
  // ------------------------------------------------------------------ KING
  KING: {
    opener: [
      'Kralj prognoza je stigao.',
      'Poklonite se, prvi na ljestvici je ušao.',
      'Pažnja, vodeći igrač je u zgradi.',
      'Evo ga, {nick} osobno.',
      'Stiže onaj koji trenutno zna sve.',
      'Prvo mjesto se upravo prijavilo.',
      'Šampion je odlučio počastiti nas posjetom.',
      'Vrh ljestvice ima ime i ono glasi {nick}.',
      'Dobro jutro, veličanstvo.',
      'Legenda hoda među nama.',
      'Vodeći je došao provjeriti je li još uvijek vodeći.',
      'Tišina, prvak govori.',
    ],
    jab: [
      'Ostali se bore za drugo mjesto.',
      'Imaš {points} i to se vidi izdaleka.',
      'Konkurencija te gleda kroz dvogled.',
      'Trenutno si {rank}. od {total} i to nije slučajnost.',
      'Ostatak ljestvice te prati sa sigurne udaljenosti.',
      'Netko mora biti prvi, ispalo je da si to ti.',
      'S {points} si postao problem za sve ostale.',
      'Drugi imaju plan, ti imaš bodove.',
      'Statistika je na tvojoj strani, barem danas.',
      'Ljestvica te je zavoljela.',
      'Tvojih {points} trenutno boli sve ostale.',
      'Prvo mjesto ti pristaje sumnjivo dobro.',
    ],
    twist: [
      'Ali ljestvica je okrutna gospođa i pamti sve.',
      'Uživaj dok traje, nogomet ne poštuje nikoga.',
      'Vrh je lijep, pad s njega manje.',
      'Naravno, jedna kriva prognoza i priča je drugačija.',
      'Prvo mjesto je posuđeno, nikad kupljeno.',
      'Hajduk ima naviku iznenaditi baš tebe.',
      'Sve je to lijepo dok ne dođe kolo koje te ne voli.',
      'Sad te svi žele pobijediti, to je jedina nagrada.',
      'Kruna je teška, pogotovo protiv Dinama.',
      'Povijest je puna vodećih koji su se opustili.',
      'Jedno kolo dijeli slavu od objašnjavanja.',
      'Vrh je najusamljenije mjesto na ljestvici.',
    ],
    closer: [
      'Prognoziraj i ostani gore.',
      'Hajde, dokaži da nije bila sreća.',
      'Idemo, kruna se ne brani sama.',
      'Upiši rezultat i nastavi vladati.',
      'Sad se pokaži još jednom.',
      'Tvoj potez, prvače.',
      'Vrijeme je za novu prognozu.',
      'Ne daj im ni centimetar.',
      'Nastavi, publika gleda.',
      'Pokaži im kako se to radi.',
      'Idemo po još jedan bod.',
      'Tipuj pa da vidimo.',
    ],
  },

  // ---------------------------------------------------------------- CHASER
  CHASER: {
    opener: [
      'Progonitelj je stigao.',
      'Evo ga {nick}, službeno gladan bodova.',
      'Netko je došao po prvo mjesto.',
      'Drugi red ljestvice se javlja.',
      'Stiže onaj koji gleda gore.',
      'Pažnja, kandidat za vrh je ušao.',
      'Blizu si, opasno blizu.',
      'Dobro došao natrag u lov.',
      'Onaj koji diše za vratom je tu.',
      'Vrh je na vidiku, {nick}.',
      'Lovac je ušao u prostoriju.',
      'Još malo pa si gore.',
    ],
    jab: [
      'Zaostaješ {gap} za prvim.',
      'Trenutno si {rank}. i to te očito živcira.',
      '{gap} te dijeli od krune.',
      'Imaš {points}, prvi ima nešto više.',
      'Blizu si koliko i daleko.',
      'Razlika je {gap} i mogla bi nestati u jednom kolu.',
      'Ljestvica te drži na drugom planu, zasad.',
      'Sve je spremno osim rezultata.',
      'Prvo mjesto je na dohvat ruke, samo je ruka kratka.',
      'S {points} si opasan, ali ne još i prvi.',
      'Fali ti točno {gap} i malo sreće.',
      'Statistika kaže da možeš, kolo kaže da moraš.',
    ],
    twist: [
      'Drugo mjesto je najfrustrirajuće mjesto na svijetu.',
      'Ali netko iza tebe ima isti plan.',
      'Naravno, i prvi zna da dolaziš.',
      'Lov je zabavan dok ne postaneš plijen.',
      'Jedna prognoza dijeli tebe i naslov.',
      'Bodovi ne padaju s neba, padaju s Poljuda.',
      'Sve ovisi o kolu koje dolazi.',
      'Prvi te vidi u retrovizoru i to mu ne smeta.',
      'Ljestvica voli obrate, budi jedan od njih.',
      'Blizu se ne broji, osim u potkovicama.',
      'Trenutak istine je sljedeća utakmica.',
      'Približavanje je lako, prestizanje nije.',
    ],
    closer: [
      'Idemo, vrh se sam neće osvojiti.',
      'Upiši prognozu i skrati razliku.',
      'Sad je trenutak.',
      'Napadni prvo mjesto.',
      'Tvoja prognoza, tvoja prilika.',
      'Hajde, prestigni ga.',
      'Vrijeme je za veliki potez.',
      'Ne daj mu da se odmori.',
      'Prognoziraj kao da je finale.',
      'Sad ili sljedeće kolo, ali radije sad.',
      'Skrati zaostatak.',
      'Idemo po prvo mjesto.',
    ],
  },

  // ------------------------------------------------------------------- HOT
  HOT: {
    opener: [
      'Netko je u naletu.',
      'Stiže {nick} u seriji.',
      'Pažnja, forma dana je ušla.',
      'Onaj koji zadnje ne promašuje je tu.',
      'Vruća ruka se prijavila.',
      'Serija se nastavlja, barem zasad.',
      'Evo ga, igrač u transu.',
      'Dobro došao, proroče.',
      'Netko je pročitao Hajduk kao knjigu.',
      'Forma je stigla i sjela za stol.',
      'Onaj koji pogađa je ušao.',
      'Stiže čovjek s nizom.',
    ],
    jab: [
      'Niz ti je {streak} i raste.',
      'Imaš {points} i pogađaš kao da imaš pristup svlačionici.',
      'Zadnjih nekoliko kola si nepogrešiv.',
      'Točnost ti je {acc}% i to počinje biti sumnjivo.',
      'Trenutno si {rank}. i penješ se.',
      'Serija od {streak} govori umjesto tebe.',
      'Ostali te gledaju s nevjericom.',
      'S {points} si postao tema razgovora.',
      'Netko je našao formulu.',
      'Ovakav niz se ne viđa često.',
      'Pogađaš rezultate koje ni trener ne bi.',
      'Tvoj niz je službeno problem za ostale.',
    ],
    twist: [
      'Ali nizovi imaju običaj završiti bez najave.',
      'Nogomet voli prekinuti baš ovakve priče.',
      'Uživaj, sreća je posudba a ne poklon.',
      'Sad je pritisak na tvojoj strani.',
      'Svaki niz ima zadnje kolo.',
      'Naravno, Hajduk zna kako pokvariti seriju.',
      'Statistika će se prije ili kasnije javiti.',
      'Ovo je trenutak kad se obično sve raspadne.',
      'Ne gledaj dolje, gledaj sljedeću utakmicu.',
      'Serija je lijepa dok se ne prekine.',
      'Sve dobro traje do prvog remija koji nisi vidio.',
      'Sad svi čekaju da promašiš.',
    ],
    closer: [
      'Nastavi niz.',
      'Idemo, još jedan pogodak.',
      'Ne kvari sad.',
      'Upiši prognozu dok ide.',
      'Serija čeka nastavak.',
      'Hajde, produži priču.',
      'Tvoj trenutak, iskoristi ga.',
      'Prognoziraj bez razmišljanja.',
      'Vjeruj instinktu, radi ti.',
      'Još jedno kolo, još jedan bod.',
      'Idemo dalje.',
      'Drži formu.',
    ],
  },

  // ----------------------------------------------------------------- SLUMP
  SLUMP: {
    opener: [
      'Vratio se onaj u krizi.',
      'Evo ga {nick}, bez bodova već neko vrijeme.',
      'Netko traži izgubljenu formu.',
      'Stiže igrač u potrazi za bodom.',
      'Dobro došao natrag, kriza te čeka.',
      'Onaj koji zadnje ne pogađa je ušao.',
      'Pažnja, suša je stigla.',
      'Evo ga, čovjek bez sreće.',
      'Vratio se, i dalje traži prvi bod ovog niza.',
      'Netko je zaboravio kako se pogađa.',
      'Stiže onaj kojem loptica ne pada.',
      'Kriza forme se prijavila.',
    ],
    jab: [
      'Bez boda već {streak} kola.',
      'Trenutno si {rank}. i pada se brže nego što se penje.',
      'Imaš {points} i to stoji na mjestu.',
      'Točnost ti je {acc}%, bila su bolja vremena.',
      'Zadnja tri kola su prošla bez traga.',
      'Ljestvica te polako zaboravlja.',
      'Zaostaješ {gap} za prvim i razlika raste.',
      'Sve prognoze su blizu, nijedna nije točna.',
      'Bodovi su te zaobišli u širokom luku.',
      'Nizovi bez boda su i dalje nizovi.',
      'S {points} si trenutno u sivoj zoni.',
      'Statistika ti trenutno nije prijatelj.',
    ],
    twist: [
      'Ali svaka suša negdje završi.',
      'Dobra vijest: gore od ovoga ide teško.',
      'Nogomet je ciklički, valjda.',
      'Jedan točan rezultat i sve je zaboravljeno.',
      'Barem si dosljedan.',
      'I najbolji imaju kola koja bi radije preskočili.',
      'Sreća se vraća onima koji nastave tipovati.',
      'Kriza je samo forma koja kasni.',
      'Hajduk je nepredvidiv, to je i tvoja isprika.',
      'Netko mora povući kratku slamku, ovaj put ti.',
      'Statistika kaže da si na redu za pogodak.',
      'Iz ovakvih serija nastaju najbolje priče.',
    ],
    closer: [
      'Prekini niz.',
      'Idemo, jedan bod je dovoljan za početak.',
      'Upiši prognozu i okreni priču.',
      'Hajde, sad ide.',
      'Vrijeme je za povratak.',
      'Pokušaj ponovno.',
      'Novo kolo, novi pokušaj.',
      'Ne odustaj sad.',
      'Tipuj i zaboravi prošlo.',
      'Idemo iz početka.',
      'Jedan pogodak mijenja sve.',
      'Daj si priliku.',
    ],
  },

  // -------------------------------------------------------------- BASEMENT
  BASEMENT: {
    opener: [
      'Gle tko je odlučio doći.',
      'Evo ga {nick}, dno ljestvice se javlja.',
      'Podrum ima novog stanara i to si ti.',
      'Netko se popeo iz zadnjeg reda.',
      'Dobro došao, temelju ljestvice.',
      'Pažnja, posljednje mjesto je online.',
      'Stiže onaj koji drži ljestvicu da ne odleti.',
      'Evo ga, čovjek koji sve druge čini sretnima.',
      'Zadnje mjesto je stiglo na vrijeme, jedino to.',
      'Netko mora biti zadnji, hvala ti na žrtvi.',
      'Vratio se naš najveći optimist.',
      'Stiže {nick}, i dalje uvjeren da ide na bolje.',
    ],
    jab: [
      'Trenutno si {rank}. od {total}.',
      'Imaš {points} i tu se priča prekida.',
      'Zaostaješ {gap} za prvim, ali tko broji.',
      'Točnost ti je {acc}% i to je zaokruženo naviše.',
      'Bez boda već {streak} kola.',
      'Ljestvica te drži na dnu iz sentimentalnih razloga.',
      'Ostali ti mašu odozgo.',
      'S {points} si službeno referentna točka.',
      'Zahvaljujući tebi svi ostali izgledaju dobro.',
      'Dno je stabilno, to ti se mora priznati.',
      'Tvoje prognoze su hrabre, samo ne i točne.',
      'Statistika te zaobilazi u širokom luku.',
    ],
    twist: [
      'Ali i pokvaren sat je točan dvaput dnevno.',
      'S dna je barem pogled prema gore.',
      'Gore od ovoga stvarno ne ide.',
      'Jedini smjer koji ti je ostao je prema gore.',
      'Netko mora zatvoriti ljestvicu, ti si dobrovoljac.',
      'Barem imaš najviše prostora za napredak.',
      'Svaka legenda je negdje počela, obično ne ovdje.',
      'Zadnje mjesto gradi karakter.',
      'Ovo je dio priče prije preokreta.',
      'Nema pritiska kad nemaš što izgubiti.',
      'Dno je udobno, ali dosadno.',
      'Sljedeće kolo je tvoja prilika za rehabilitaciju.',
    ],
    closer: [
      'Hajde, jedan bod ove sezone.',
      'Upiši prognozu, možda te iznenadi.',
      'Idemo, dno se ne mora braniti.',
      'Pokušaj barem ovaj put.',
      'Novo kolo, nova nada.',
      'Tipuj, gore ne može.',
      'Vrijeme je za prvi pogodak.',
      'Daj sve od sebe, publika je milostiva.',
      'Idemo po povijesni bod.',
      'Prognoziraj i dokaži da si tu.',
      'Sad ozbiljno, hajde.',
      'Jedan pogodak i ljudi će pričati.',
    ],
  },

  // -------------------------------------------------------------- MEDIOCRE
  MEDIOCRE: {
    opener: [
      'Evo ga, sigurno skriven u sredini.',
      'Stiže {nick}, službeno prosječan.',
      'Sredina ljestvice se javlja.',
      'Netko iz zlatne sredine je ušao.',
      'Dobro došao u zonu bez uzbuđenja.',
      'Pažnja, prosjek je stigao.',
      'Evo ga, čovjek koji nikoga ne uznemirava.',
      'Stiže igrač bez ekstrema.',
      'Sredina je stabilna zahvaljujući tebi.',
      'Vratio se naš specijalist za sredinu tablice.',
      'Netko je pronašao savršenu ravnotežu između dobrog i lošeg.',
      'Stiže {nick}, ni gore ni dolje.',
    ],
    jab: [
      'Trenutno si {rank}. od {total}.',
      'Imaš {points} i to je točno prosjek.',
      'Zaostaješ {gap} za prvim.',
      'Točnost ti je {acc}%, ni sjajno ni tragično.',
      'Ni prvi ni zadnji, savršeno neupadljivo.',
      'Ljestvica te ne primjećuje i to je kompliment.',
      'S {points} si u zoni potpune sigurnosti.',
      'Nitko ne priča o tebi, a to nešto govori.',
      'Sredina je udobna, priznaj.',
      'Dovoljno dobar da nisi zadnji, dovoljno loš da nisi prvi.',
      'Tvoja pozicija je definicija stabilnosti.',
      'Do vrha ti fali {gap}, do dna više od toga.',
    ],
    twist: [
      'Ali jedna dobra prognoza te izbacuje iz anonimnosti.',
      'Sredina je sigurna, ali nitko se ne sjeća sredine.',
      'Prosjek je izbor, ne sudbina.',
      'Vrh je bliže nego što misliš.',
      'Netko iza tebe planira napad.',
      'Sredina se najlakše napusti prema gore.',
      'Sigurnost je precijenjena.',
      'Ovo je kolo u kojem se obično nešto promijeni.',
      'Jedan pogodak i pričamo drugu priču.',
      'Prosjek je samo trenutno stanje.',
      'Nitko nije zapamćen po sedmom mjestu.',
      'Ljestvica čeka da napraviš potez.',
    ],
    closer: [
      'Izađi iz sredine.',
      'Idemo, jedan skok prema gore.',
      'Upiši prognozu i napravi nered.',
      'Vrijeme je za nešto veće.',
      'Hajde, iznenadi nas.',
      'Napadni vrh.',
      'Prognoziraj hrabro.',
      'Sad je prilika.',
      'Tipuj pa da vidimo tko si.',
      'Idemo iz sredine prema gore.',
      'Ovo kolo može sve promijeniti.',
      'Daj im razloga da pričaju o tebi.',
    ],
  },

  // -------------------------------------------------------------- CLIMBER
  CLIMBER: {
    opener: [
      'Netko se penje.',
      'Stiže {nick}, u usponu.',
      'Pažnja, ljestvica se pomaknula u tvoju korist.',
      'Evo ga, čovjek koji ide prema gore.',
      'Dobro došao, penjaču.',
      'Netko je preskočio par mjesta.',
      'Uspon je službeno počeo.',
      'Stiže igrač s dobrim vjetrom u leđa.',
      'Ljestvica te je gurnula naprijed.',
      'Evo ga, {nick} u pokretu.',
      'Netko je pronašao stepenice.',
      'Kretanje prema gore je zabilježeno.',
    ],
    jab: [
      'Sad si {rank}. od {total}.',
      'Imaš {points} i raste.',
      'Zaostaješ još {gap} za prvim.',
      'Točnost ti je {acc}% i ide u dobrom smjeru.',
      'Netko ispod tebe je manje sretan zbog toga.',
      'Uspon je stvaran, ne slučajan.',
      'S {points} si postao zanimljiv.',
      'Ljestvica te napokon primijetila.',
      'Do sljedećeg mjesta ti fali {gapNext}.',
      'Kretanje prema gore je najbolja vrsta kretanja.',
      'Konkurencija se počinje osvrtati.',
      'Trend je tvoj prijatelj ovog trenutka.',
    ],
    twist: [
      'Ali uspon se lako pretvori u pad.',
      'Sad te treba zadržati gore.',
      'Penjanje je lakše od ostajanja.',
      'Naravno, i drugi imaju isti plan.',
      'Ljestvica pamti i uspone i padove.',
      'Jedno slabo kolo i vraćaš se odakle si došao.',
      'Uspon bez nastavka je samo epizoda.',
      'Sad počinje pravi dio.',
      'Nogomet voli kazniti opuštanje.',
      'Dobar trend traži potvrdu.',
      'Sljedeća utakmica je test.',
      'Nemoj sad stati.',
    ],
    closer: [
      'Nastavi prema gore.',
      'Idemo, još jedno mjesto.',
      'Upiši prognozu i drži tempo.',
      'Uspon se ne zaustavlja sam.',
      'Hajde, još malo.',
      'Zadrži smjer.',
      'Tvoj potez.',
      'Prognoziraj i penji se dalje.',
      'Ne stani sad.',
      'Idemo po još.',
      'Vrijeme je za novi skok.',
      'Nastavi tako.',
    ],
  },

  // --------------------------------------------------------------- ROOKIE
  ROOKIE: {
    opener: [
      'Novo lice na ljestvici.',
      'Dobro došao, {nick}.',
      'Stiže netko nov.',
      'Pažnja, novajlija je ušao.',
      'Evo ga, prvi koraci.',
      'Netko je odlučio pokušati.',
      'Dobro došao u društvo.',
      'Stiže svježa krv.',
      'Novi igrač se prijavio.',
      'Evo ga {nick}, još bez povijesti.',
      'Netko počinje ispočetka.',
      'Dobro došao na Poljud, digitalno.',
    ],
    jab: [
      'Imaš {points} i cijelu sezonu ispred sebe.',
      'Trenutno si {rank}. od {total}, ali to još ništa ne znači.',
      'Statistika te još ne poznaje.',
      'Prekratko si tu da bi te itko ozbiljno shvatio.',
      'Nekoliko utakmica dijeli te od prve ozbiljne ocjene.',
      'Tvoj dosje je i dalje prazan.',
      'Nitko još ne zna jesi li dobar ili sretan.',
      'S {points} si na startnoj poziciji.',
      'Ljestvica te tek upoznaje.',
      'Prva ozbiljna procjena stiže za koje kolo.',
      'Za sada si misterij.',
      'Sve je još otvoreno.',
    ],
    twist: [
      'Dobra vijest: svi su nekad počeli ovdje.',
      'Početnička sreća je stvarna, koristi je.',
      'Nemaš što izgubiti, to je prednost.',
      'Najbolji su nekad bili baš tu gdje si ti.',
      'Prvi pogodak je najslađi.',
      'Nitko ne očekuje ništa, savršena pozicija.',
      'Iskusni igrači se boje upravo novajlija.',
      'Bez pritiska se najbolje prognozira.',
      'Sve legende počinju s nula bodova.',
      'Sezona je duga, prostora ima.',
      'Ovo je najbolji trenutak za smjelu prognozu.',
      'Iznenađenja obično dolaze od novih.',
    ],
    closer: [
      'Upiši prvu prognozu.',
      'Idemo, pokaži što znaš.',
      'Hajde, počni.',
      'Vrijeme je za prvi bod.',
      'Tipuj bez straha.',
      'Prognoziraj i uđi u priču.',
      'Sad se predstavi.',
      'Neka prva bude dobra.',
      'Idemo od početka.',
      'Daj svoj rezultat.',
      'Pokaži im.',
      'Sretno, trebat će ti.',
    ],
  },
};

/** Sanity bound used by tests: every tone must offer at least this many options. */
export const MIN_VARIANTS_PER_SLOT = 10;
